# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "a5bb400cdede8cb9bffdc8ff8d8e90eb"
name = "Wishlist App"
handle = "wishlist-app-345"
application_url = "https://designing-brooklyn-date-essay.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://designing-brooklyn-date-essay.trycloudflare.com/auth/callback",
  "https://designing-brooklyn-date-essay.trycloudflare.com/auth/shopify/callback",
  "https://designing-brooklyn-date-essay.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
